# 2.x
# Docker Configtx
# Sets up the 3 orgs in the network

# CAPABILITIES
Capabilities:
  Application: &ApplicationCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Channel: &ChannelCapabilities
    V2_0: true

# ORGANIZATIONS
Organizations:
  - &Orderer
    Name: Orderer
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/hospital.com/msp
    Policies: &OrdererPolicies
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"

  - &Hospital
    Name: Hospital
    ID: HospitalMSP
    MSPDir: ./crypto-config/peerOrganizations/hospital.com/msp
    Policies: &HospitalPolicies
      Readers:
        Type: Signature
        Rule: "OR('HospitalMSP.admin', 'HospitalMSP.peer', 'HospitalMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('HospitalMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('HospitalMSP.admin','OrdererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('HospitalMSP.member')"
    AnchorPeers:
      - Host: peer1.hospital.com
        Port: 7051

  - &Customer
    Name: Customer
    ID: CustomerMSP
    MSPDir: ./crypto-config/peerOrganizations/customer.com/msp
    Policies: &CustomerPolicies
      Readers:
        Type: Signature
        Rule: "OR('CustomerMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('CustomerMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('CustomerMSP.member')"
      Endorsement:
        Type: Signature
        Rule: "OR('CustomerMSP.member')"
    AnchorPeers:
      - Host: peer1.customer.com
        Port: 8051

  - &Pharmacy
    Name: Pharmacy
    ID: PharmacyMSP
    MSPDir: ./crypto-config/peerOrganizations/pharmacy.com/msp
    Policies: &PharmacyPolicies
      Readers:
        Type: Signature
        Rule: "OR('PharmacyMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('PharmacyMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('PharmacyMSP.member')"
      Endorsement:
        Type: Signature
        Rule: "OR('PharmacyMSP.member')"
    AnchorPeers:
      - Host: peer1.pharmacy.com
        Port: 9051

  - &Delivery
    Name: Delivery
    ID: DeliveryMSP
    MSPDir: ./crypto-config/peerOrganizations/delivery.com/msp
    Policies: &DeliveryPolicies
      Readers:
        Type: Signature
        Rule: "OR('DeliveryMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('DeliveryMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('DeliveryMSP.member')"
      Endorsement:
        Type: Signature
        Rule: "OR('DeliveryMSP.member')"
    AnchorPeers:
      - Host: peer1.delivery.com
        Port: 10051

# ORDERER
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.hospital.com:7050
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB
  Capabilities:
    <<: *OrdererCapabilities

# APPLICATION
Application: &ApplicationDefaults
  ACLs: &ACLsDefault
    lscc/ChaincodeExists: /Channel/Application/Readers
    lscc/GetDeploymentSpec: /Channel/Application/Readers
    lscc/GetChaincodeData: /Channel/Application/Readers
    lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
    qscc/GetChainInfo: /Channel/Application/Readers
    qscc/GetBlockByNumber: /Channel/Application/Readers
    qscc/GetBlockByHash: /Channel/Application/Readers
    qscc/GetTransactionByID: /Channel/Application/Readers
    qscc/GetBlockByTxID: /Channel/Application/Readers
    cscc/GetConfigBlock: /Channel/Application/Readers
    cscc/GetConfigTree: /Channel/Application/Readers
    cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers
    peer/Propose: /Channel/Application/Writers
    peer/ChaincodeToChaincode: /Channel/Application/Readers
    event/Block: /Channel/Application/Readers
    event/FilteredBlock: /Channel/Application/Readers
    _lifecycle/CheckCommitReadiness: /Channel/Application/Writers
    _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
    _lifecycle/QueryChaincodeDefinition: /Channel/Application/Readers
  Policies: &ApplicationDefaultPolicies
    Endorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
  Organizations:
  Capabilities:
    <<: *ApplicationCapabilities

# CHANNEL
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ChannelCapabilities

# PROFILES
Profiles:

  MedlineOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - <<: *Orderer
    Consortiums:
      MedlineConsortium:
        Organizations:
          - <<: *Hospital
          - <<: *Customer
          - <<: *Pharmacy
          - <<: *Delivery

  MedlineChannel:
    <<: *ChannelDefaults
    Consortium: MedlineConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - <<: *Customer
        - <<: *Pharmacy
        - <<: *Delivery

  PrescVerChannel:
    <<: *ChannelDefaults
    Consortium: MedlineConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - <<: *Hospital
        - <<: *Customer
        - <<: *Pharmacy

  PharmaFulChannel:
    <<: *ChannelDefaults
    Consortium: MedlineConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - <<: *Pharmacy
        - <<: *Delivery

  DeliveryChannel:
    <<: *ChannelDefaults
    Consortium: MedlineConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - <<: *Customer
        - <<: *Delivery