
version: '2'

networks:
  medline:

# Storage outside the containers
volumes:
  data-orderer.hospital.com:
  data-peer1.hospital.com:
  data-peer1.customer.com:
  data-peer1.pharmacy.com:
  data-peer1.delivery.com:

services:

  # Orderer service
  orderer.hospital.com:
    container_name: orderer.hospital.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    command: orderer
    # Override environment variables for orderer in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=INFO
    # Host folder mappings
    volumes:
    # Folder with genesis block
    - ${PWD}/orderer:/var/hyperledger/config
    # Map the folder with MSP for orderer
    - ${PWD}/crypto-config/ordererOrganizations/hospital.com/orderers/orderer.hospital.com/msp:/var/hyperledger/msp
    # Added to support the TLS setup
    - ${PWD}/crypto-config/ordererOrganizations/hospital.com/orderers/orderer.hospital.com/tls:/var/hyperledger/tls
    - data-orderer.hospital.com:/var/ledger
    ports:
      - 7050:7050
    networks:
      - medline

  # Hospital peer1
  peer1.hospital.com:
    container_name: peer1.hospital.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    # Override variables in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_medline
    # Start the peer node
    command: peer node start
    # Host folder mappings
    volumes:
      # Folder with channel create tx file
      - ${PWD}/hospital:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - ${PWD}/crypto-config/peerOrganizations/hospital.com/peers/peer1.hospital.com/msp:/var/hyperledger/msp
      # Added to support the TLS setup
      - ${PWD}/crypto-config/peerOrganizations/hospital.com/peers/peer1.hospital.com/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.hospital.com:/var/hyperledger/production
    depends_on: 
      - orderer.hospital.com
    # Map the ports on Host VM to container ports
    ports:
      - 7051:7051
      - 7052:7052
    networks:
      - medline

  #  customer peer1
  peer1.customer.com:
    container_name: peer1.customer.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    # landing directory
    working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start
    # Environment setup for peer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - GOPATH=/opt/gopath
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_medline
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.customer.com:7051
    # host file system mappings
    volumes:
      # Folder with channel create tx file
      - ${PWD}/customer:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - ${PWD}/crypto-config/peerOrganizations/customer.com/peers/peer1.customer.com/msp:/var/hyperledger/msp
      # Added to support the TLS setup
      - ${PWD}/crypto-config/peerOrganizations/customer.com/peers/peer1.customer.com/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.customer.com:/var/hyperledger/production
    depends_on: 
      - orderer.hospital.com
    # Map the ports on Host VM to container ports
    ports:
      - 8051:7051
      - 8052:7052
    networks:
      - medline

  peer1.pharmacy.com:
    container_name: peer1.pharmacy.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    # landing directory
    working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start
    # Environment setup for peer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - GOPATH=/opt/gopath
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_medline
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.pharmacy.com:7051
    # host file system mappings
    volumes:
      # Folder with channel create tx file
      - ${PWD}/pharmacy:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - ${PWD}/crypto-config/peerOrganizations/pharmacy.com/peers/peer1.pharmacy.com/msp:/var/hyperledger/msp
      # Added to support the TLS setup
      - ${PWD}/crypto-config/peerOrganizations/pharmacy.com/peers/peer1.pharmacy.com/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.pharmacy.com:/var/hyperledger/production
    depends_on: 
      - orderer.hospital.com
    # Map the ports on Host VM to container ports
    ports:
      - 9051:7051
      - 9052:7052
    networks:
      - medline
    
  peer1.delivery.com:
    container_name: peer1.delivery.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    # landing directory
    working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start
    # Environment setup for peer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - GOPATH=/opt/gopath
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_medline
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.delivery.com:7051
    # host file system mappings
    volumes:
      # Folder with channel create tx file
      - ${PWD}/delivery:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - ${PWD}/crypto-config/peerOrganizations/delivery.com/peers/peer1.delivery.com/msp:/var/hyperledger/msp
      # Added to support the TLS setup
      - ${PWD}/crypto-config/peerOrganizations/delivery.com/peers/peer1.delivery.com/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.delivery.com:/var/hyperledger/production
    depends_on: 
      - orderer.hospital.com
    # Map the ports on Host VM to container ports
    ports:
      - 10051:7051
      - 10052:7052
    networks:
      - medline

  # Tools container used for managing peers
  tools:
    container_name: tools
    command: /bin/bash

    # Tools container image
    image: hyperledger/fabric-tools:$IMAGE_TAG

    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
    # This is the working directory on login
    working_dir: /opt/scripts
    volumes:
      # Mapping for the sample chaincode folders
      - ${PWD}/../artefacts/nodechaincode:/opt/nodechaincode
      - ${PWD}/../gopath:/opt/gopath
      # Folder with channel create tx file
      - ${PWD}:/var/hyperledger/config
      # Map the folder to root of all Fabric CA Client crypto
      - ${PWD}/crypto-config/peerOrganizations:/var/hyperledger/crypto
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Map the bins folder
      - ${PWD}/tool-bins:/opt/scripts
    networks:
      - medline
  
  