version: '2'

networks:
  medline:

services:
  ca_hospital:
    image: hyperledger/fabric-ca:latest
    container_name: ca-hospital
    environment:
      - FABRIC_CA_HOME=/var/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hospital
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - /home/linto/Project_new/network/ca/server:/var/hyperledger/fabric-ca-server
    networks:
      - medline
